# Setup
# title: Dark Poole
# url: https://getpoole.com
# permalink: pretty
# permalink: none
# pretty_urls:
#   enabled: false




# GitHub Pages settings for Docs Assembler 
# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
baseurl: ""
markdown_ext: markdown,tsfrg,md
sass:
  sass_dir: _sass
  style: :compressed
