# Permalinks
permalink:        pretty

# Setup
title: Docs Assembler demo guides
url:              https://marketplace.visualstudio.com/items?itemName=netoftrees.documentation-assembler
baseurl:          /
markdown_ext: markdown,tsfrg,md


